import Load from '../models/load.model.js';

export const seedLoads = async () => {
await Load.create({
  reference_id: "DAT-1000",
  company: "Tucker-Khan",
  email: "courtney73@richardson-eaton.com",
  broker_name: "Tammy Baldwin",
  call_count: 3,
  rate: 2028,
  worked_with_us_before: true,
  from_location: "New Bernardport, VT",
  to_location: "Port Bailey, UT",
  total_pounds: 48000,
  pickup_places: ["Valdezport"],
  delivery_places: ["Jessicastad"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1689,
  fcfs: true,
  type: "Dry",
  comments: "Politics increase understand add instead campaign would.",
  price_bought: 2062,
  price_sold: 3833,
  current_location: "NC",
  next_location: "DC",
  is_from_rigz: false,
  nationality: "Russian",
  notes: "Particularly compare go go.",
});
await Load.create({
  reference_id: "DAT-1001",
  company: "Frazier Inc",
  email: "scott10@gonzalez-page.com",
  broker_name: "Luis Williams",
  call_count: 1,
  rate: 3138,
  worked_with_us_before: false,
  from_location: "Schmidtview, MO",
  to_location: "South Mary, ND",
  total_pounds: 35000,
  pickup_places: ["West Anna"],
  delivery_places: ["Brittneyside"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1393,
  fcfs: true,
  type: "Van",
  comments: "Necessary put partner read.",
  price_bought: 2784,
  price_sold: 3695,
  current_location: "SD",
  next_location: "SC",
  is_from_rigz: true,
  nationality: "Pakistani",
  notes: "Service radio six choice speak.",
});
await Load.create({
  reference_id: "DAT-1002",
  company: "Rice, Smith and Herring",
  email: "alexandra93@jones.net",
  broker_name: "Karen Miller",
  call_count: 5,
  rate: 2449,
  worked_with_us_before: true,
  from_location: "Melindaland, CA",
  to_location: "Hodgesland, KS",
  total_pounds: 48000,
  pickup_places: ["Graymouth"],
  delivery_places: ["Hectormouth"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1341,
  fcfs: true,
  type: "Van",
  comments: "Alone understand next white western movie strong road.",
  price_bought: 2600,
  price_sold: 3910,
  current_location: "MA",
  next_location: "VA",
  is_from_rigz: true,
  nationality: "Chinese",
  notes: "Its rate issue number.",
});
await Load.create({
  reference_id: "DAT-1003",
  company: "Moreno PLC",
  email: "amandawilliams@watson.com",
  broker_name: "Richard Mendoza",
  call_count: 2,
  rate: 2856,
  worked_with_us_before: false,
  from_location: "Patriciaville, LA",
  to_location: "Tammystad, WY",
  total_pounds: 48000,
  pickup_places: ["West Jeffreytown"],
  delivery_places: ["Williamton"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1440,
  fcfs: false,
  type: "Van or Reefer",
  comments: "Energy decide arrive southern reality point.",
  price_bought: 2644,
  price_sold: 3779,
  current_location: "FL",
  next_location: "PA",
  is_from_rigz: true,
  nationality: "American",
  notes: "See training dark attorney simple truth.",
});
await Load.create({
  reference_id: "DAT-1004",
  company: "Holmes, Morgan and Carroll",
  email: "laura08@ray-collins.com",
  broker_name: "Laurie Smith",
  call_count: 4,
  rate: 3244,
  worked_with_us_before: true,
  from_location: "Joseland, PA",
  to_location: "Bakerland, IN",
  total_pounds: 35000,
  pickup_places: ["Christinaside"],
  delivery_places: ["North Michelle"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1748,
  fcfs: true,
  type: "Dry",
  comments: "Discussion research cold on explain agree.",
  price_bought: 2895,
  price_sold: 3113,
  current_location: "KY",
  next_location: "NE",
  is_from_rigz: false,
  nationality: "Pakistani",
  notes: "Fill truth trade to ok.",
});
await Load.create({
  reference_id: "DAT-1005",
  company: "Baker Inc",
  email: "loconnor@gonzalez.com",
  broker_name: "Gina Garcia",
  call_count: 5,
  rate: 2972,
  worked_with_us_before: true,
  from_location: "North Territon, MD",
  to_location: "Davidberg, AL",
  total_pounds: 48000,
  pickup_places: ["Ryanmouth"],
  delivery_places: ["Stevenhaven"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1961,
  fcfs: false,
  type: "Van or Reefer",
  comments: "Among ahead song grow.",
  price_bought: 2844,
  price_sold: 3775,
  current_location: "CT",
  next_location: "AK",
  is_from_rigz: false,
  nationality: "Chinese",
  notes: "Him six lose note near.",
});
await Load.create({
  reference_id: "DAT-1006",
  company: "Zamora-Anderson",
  email: "julie16@joyce.info",
  broker_name: "Jennifer Valdez",
  call_count: 2,
  rate: 2646,
  worked_with_us_before: true,
  from_location: "Amandaport, ID",
  to_location: "Port Jennifer, TN",
  total_pounds: 42000,
  pickup_places: ["Lake Joshua"],
  delivery_places: ["New Nicholas"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1405,
  fcfs: false,
  type: "Van or Reefer",
  comments: "Defense soldier pretty American.",
  price_bought: 2297,
  price_sold: 3724,
  current_location: "DC",
  next_location: "MO",
  is_from_rigz: false,
  nationality: "Chinese",
  notes: "Can bank available free better well whatever.",
});
await Load.create({
  reference_id: "DAT-1007",
  company: "Hess Inc",
  email: "zacharybuchanan@alvarez.com",
  broker_name: "Sarah Walton",
  call_count: 3,
  rate: 3974,
  worked_with_us_before: true,
  from_location: "Hunterstad, KY",
  to_location: "Burgessview, NV",
  total_pounds: 35000,
  pickup_places: ["West Jessica"],
  delivery_places: ["Terrimouth"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1035,
  fcfs: false,
  type: "Dry",
  comments: "Position voice man.",
  price_bought: 2619,
  price_sold: 3794,
  current_location: "NM",
  next_location: "AL",
  is_from_rigz: false,
  nationality: "Irish",
  notes: "Plant argue modern.",
});
await Load.create({
  reference_id: "DAT-1008",
  company: "Ferrell, Walters and Casey",
  email: "cassandra69@rich.org",
  broker_name: "Vincent Gonzalez",
  call_count: 3,
  rate: 2954,
  worked_with_us_before: false,
  from_location: "Lake Amy, OR",
  to_location: "Matthewsport, AL",
  total_pounds: 35000,
  pickup_places: ["Bennetthaven"],
  delivery_places: ["Schneiderchester"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1451,
  fcfs: true,
  type: "Van or Reefer",
  comments: "View soldier use relate.",
  price_bought: 2304,
  price_sold: 3212,
  current_location: "ME",
  next_location: "IL",
  is_from_rigz: false,
  nationality: "Egyptian",
  notes: "None instead bank project read include.",
});
await Load.create({
  reference_id: "DAT-1009",
  company: "Allen, Robertson and Hendricks",
  email: "ywallace@morgan-perry.com",
  broker_name: "Julie Jones",
  call_count: 5,
  rate: 3289,
  worked_with_us_before: false,
  from_location: "Port Ashley, AK",
  to_location: "Lake Dawn, HI",
  total_pounds: 48000,
  pickup_places: ["North Michaelview"],
  delivery_places: ["Port Jack"],
  pickup_count: 1,
  delivery_count: 1,
  total_distance: 1648,
  fcfs: true,
  type: "Van",
  comments: "Senior character exist factor expert involve high.",
  price_bought: 2892,
  price_sold: 3189,
  current_location: "DE",
  next_location: "VT",
  is_from_rigz: false,
  nationality: "Russian",
  notes: "Policy health that goal member clear.",
});
};